_wandb:
    value:
        cli_version: 0.19.7
        m:
            - "1": train_total_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train_recon_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_vq_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
                - 98
                - 106
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
                - 98
                - 106
            "3":
                - 1
                - 7
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.0
            "5": 0.19.7
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
