_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
architecture:
    value: SVSAE
batch_size:
    value: 16
dataset_size:
    value: null
device:
    value: cuda
epochs:
    value: 1
learning_rate:
    value: 0.001
loss_weights:
    value:
        chamfer: 0.5
        iou: 0.5
        mse: 1
